METADATA_STORAGE_FILEPATH = "./metadata/state.json"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LIMIT_SAVE_INTERVALS = True
DEFAULT_SAVE_COOLDOWN_SEC = 300
DEFAULT_MASTER_BRANCH = "master"
APP_VERSION = "0.1.0"
DAEMON_PORT_RANGE_MIN = 1024
DAEMON_PORT_RANGE_MAX = 49151
